name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements.txt

    - name: Make .ssh directory
      run: |
        mkdir -p ~/.ssh

    - name: Setup ~/.ssh/config
      run: |
        cat << "EOF" > ~/.ssh/config
        ${{ secrets.SSH_CONFIG }}
        EOF
        chmod 644 ~/.ssh/config

    - name: Setup private key
      run: |
        cat << "EOF" > ~/.ssh/private_key
        ${{ secrets.PRIVATE_KEY }}
        EOF
        chmod 600 ~/.ssh/private_key
        eval `ssh-agent`
        ssh-add ~/.ssh/private_key

    - name: Deployment
      run: |
        fab deploy
